# Generated by Django 5.1.3 on 2024-11-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='name',
            field=models.CharField(default='Unnamed Laptop', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='photo',
            field=models.ImageField(upload_to='laptops/'),
        ),
    ]
