# Generated by Django 5.1.2 on 2024-11-09 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_laptop_description_laptop_name_alter_laptop_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_complete',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account_number',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_name',
            field=models.CharField(default='Anonymous Buyer', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_of_purchase',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
