# Generated by Django 5.1.2 on 2024-11-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_is_complete_transaction_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_account_name',
            field=models.CharField(default='No Account Name Provided', max_length=100),
        ),
    ]
