# Generated by Django 5.1.3 on 2024-11-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_is_sold_laptop_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
