# Generated by Django 5.1.3 on 2024-11-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_laptop_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='laptop_images/'),
        ),
    ]
